##
# Run unit test and the action itself
##
name: test
on:
  pull_request:
  push:

jobs:
  # test action works
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["latest", "v1.19.5"]
        catalog: ["./testdata/catalog", "quay.io/joelanford/example-operator-index:0.2.0"]
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        version: ${{ matrix.version }}
        catalog: ${{ matrix.catalog }}
